name: qr_server
description: A simple QR code server by Adedo Abdulraman and E2
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  
dependencies:
  sqlite3: ^1.3.0
  crypto: ^3.0.6
  uuid: ^4.0.0